#!/usr/bin/python3
def raise_exception():
    a = 4
    b = "Boy"
    return a/b
